openapi: 3.0.3
info:
  title: fdi-api-public
  version: 1.0.0
paths:
  '/v1/ping':
    get:
      summary: Endpoint para probar el funcionamiento del API
      description: 
        Devuelve un HTTP 200 en caso que el API esté activo y
        funcionando correctamente.
      operationId: ping
      x-router-controller: ApiController
      responses:
        '200':
          description: 'Ping exitoso'
#components:
#  securitySchemes:
#    ApiKeyAuth:
#      type: apiKey
#      in: header
#      name: X-API-Key
#security:
#  - ApiKeyAuth: []